### PR TITLE
Feature/friendship request

### PR DESCRIPTION
**Pull request by fernandorpm**
# Milestone 2: Friendships v1

## To add
- Friendship model, controller, view and migration

### CODE REVIEW

**Review by BrianSammit — COMMENTED** [review]
CHANGES REQUIRED :red_circle: :stop_sign: 
-------------
Hello, @fernandorpm great job working on this milestone. :clap: 
TO HIGHLIGHT: 

- Your project looks professional. 
- Your repo looks professional
- Well structured files
- Your linters are well configured

However, there are a few changes to make to complete this milestone. :hammer_and_wrench: see them below :eyes: :point_down: 
----------------------
- [x] I can see all the posts including the post written by not friends. Please fix this, I must be able to see the post only from my friends.

friends_timeline

- [x] I cannot see the friendships requests. Please fix this. 

pending_request

- [x] Because of the above. I cannot reject or accept a friend request. 
- [x] Please add Unit and Integration tests. 
--------------
Please make the required changes and send ti again for another review :100: :muscle: 
Reachme on SLACK if you have any questions. 
@ Brian Sammit Cruz Rodriguez
HAPPY CODING!!

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# Status: Changes required👈
Job well done so far, you have implemented almost all the changes the previous reviewer requested.

**To highlight**
- I can only see posts done by me and for users who are my friends, keep it up.
- I can accept/reject a friendship request
- I can send a friendship request
- I can see pending requests
<hr>

**Changes to make**

- [x] Some tests are failing for user, as you can see from the image below
test

<hr>

**[OPTIONAL]**

1. You can also include a button to unfriend a friendship on a user friend profile.
2. You can as well create a link on a friend profile, like "you are friends" just to be sure who my friends are.

**Comment by fernandorpm** [comment]
# To the next reviewer

The tests were working, but please be sure to use the versions proposed at the readme file:
- ruby >= 2.7.2
- rails >= 6.1.3.1

image

**Review by SajjadAhmad14 — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:

## Congratulations 🎉 Thank you for implementing changes suggested previously 🙏
# Optional but highly recommended
- [x] Please add integration tests for friendship features.
### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

**Pull request merged**
